[workspace]
resolver = "2"
members = [
    "crates/ofa-protocol",
    "crates/ofa-core",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "UNLICENSED"
publish = false

[workspace.dependencies]
ofa-protocol = { path = "crates/ofa-protocol" }
ofa-core = { path = "crates/ofa-core" }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
